### PR TITLE
Slider options

### PR DESCRIPTION
**Pull request by cooperq**

### CODE REVIEW

**Comment by cooperq** [comment]
One issue with this for @SwartzCr 
When a slider in the options page is moved from green (Seen third parties) to userRed it does not stay there. When you reload the page that tracker is on, it moves back to green. I can demo this for you tomorrow if you want.

**Comment by SwartzCr** [comment]
There seems to be an intermittent issue with FrequencyHeuristics.knownSubscriptions.seenThirdParties.parties being instantiated, a checking and instantiation function should be added as well

**Comment by cooperq** [comment]
`FrequencyHeuristics.knownSubscriptions.seenThirdParties.parties` gets instantiated in the `migrate_version` function located at https://github.com/EFForg/privacybadgerchrome/blob/master/src/background.js#L107 

That function gets called when the version number is updated. This should be sufficient for upgrading users to the new version.

**Comment by cooperq** [comment]
LGTM, other than a bunch of style nits which I think were artifacts from ABP. I will fix those.

**Pull request merged**
