### PR TITLE
Added Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by cooperq** [comment]
This looks good except for one thing, your use of double quotes around certain words will not work. Please either use a backslash to escape the quotes or put the words in single quotes. Thank you!

**Comment by TotalCaesar659** [comment]
OK, I fixed the quotes inside of strings, but Travis can't build it, I don't know why.

**Comment by rcutmore** [comment]
@TotalCaesar659 Travis is failing because it needs to use a newer version of Ubuntu, not because of your changes.

**Comment by cooperq** [comment]
Yep, this looks good to me. Thanks @TotalCaesar659 !

**Pull request merged**
