### PR TITLE
Use QUnit npm package instead.

### PR DESCRIPTION
**Pull request by duggiefresh**
* Removes checking in QUnit dependencies into source.

### CODE REVIEW

**Comment by duggiefresh** [comment]
This removes QUnit from source. Since this project is using `npm`, folks can install QUnit locally using `npm install`.

I can look into setting up PhantomJS for this project, but it might be tricky because of all the global `chrome` references.

**Comment by duggiefresh** [comment]
Strange. Selenium tests pass locally, will check on this later.

**Comment by gunesacar** [comment]
I believe you just need to add `npm install` to Travis setup scripts, e.g.:
https://github.com/gunesacar/privacybadgerchrome/compare/38158acf3628...ab89ae8797db
https://travis-ci.org/gunesacar/privacybadgerchrome/builds/69711238

**Comment by duggiefresh** [comment]
@gunesacar Ooohhh... good call. I've just added `npm install` to the `travis.yml` file. Thanks for the :eyes:!

**Comment by cooperq** [comment]
Thanks @duggiefresh, excellent work! :+1:

**Pull request merged**
