### PR TITLE
Followup to #982 (Adding ability to import and export tracker list)

### PR DESCRIPTION
**Pull request by ghostwords**
@alexristich @cooperq Let me know what you guys think.

### CODE REVIEW

**Comment by alexristich** [comment]
Exported filename stuff looks way better! Took me a while to tweak it, but never really got it to the point where the code seemed easy and readable. Much improved!

For the refactoring of recordPrevalence, I went back and forth a few times on which was better. I ended up choosing the 2 parameter solution, as it seemed like it might be easier to use moving forward in future cases where the function needs to be called from other places in the code. That being said, you're right about the hot path, and we should probably tweak it in that case such that all three parameters are passed in from the start.

**Comment by ghostwords** [comment]
[Here is a compare view link](https://github.com/EFForg/privacybadgerchrome/compare/3027137a8f74e309a31524d1a6a58a4b1ba9bf4c%5E...export-data-followup#diff-371a25d24420e6ab916c81f0c03d8f7c) to review changes between right before merge of "download" branch and this pull request.

**Comment by alexristich** [comment]
Excellent :) Good call too on simplifying the names for the parameters, though I'm thinking camel case might be more consistent in terms of style rather than underscore word splitting. Otherwise seems good to me!

**Comment by cooperq** [comment]
LGTM

**Comment by alexristich** [comment]
Wanted to document our discussion on the style. We thought it was a good idea to switch to the convention of having lowercase and underscores for primitive types, but decided to put this on the back burner for now. May migrate style document from the `privacybadgerfirefox` project, then add rules to ESLint to enforce this at a stage when someone has time to go through and refactor the code base.

**Pull request merged**
