### PR TITLE
Changing to check for length in cases where list is 'undefined'

### PR DESCRIPTION
**Pull request by alexristich**
This is a fix for #920. When an array has length 0, its value is not `null`, so the check to exit early was not functional.

### CODE REVIEW

**Comment by alexristich** [comment]
Seems like a suboptimal solution here, but with just the check `trackerInfo.length === 0` it was still displaying intermittent errors in the console. The second commit explicitly checks for an undefined value _before_ checking the length of the array.

**Comment by ghostwords** [comment]
If `trackerInfo` is an empty array, it's not null but there shouldn't be any errors. The `forEach` loop would just run zero times, for example: `[].forEach(x => console.log(x))`.

Does the problem happen when `trackerInfo` is `undefined`? When does this take place?

**Comment by alexristich** [comment]
Good question. It does happen when `trackerInfo` is `undefined`, which is what the original report shows in the error message that was displayed. Maybe the check just needs to be for a value of `undefined`? As to when this happens, I'm not really too sure. The value for `trackerInfo` is set as the result of the value returned in `trackers` in `getSocialWidgetBlockList()` from `webrequest.js`. I don't really understand how the value of `window.SocialWidgetList` would be `undefined` though. Any ideas?

**Comment by ghostwords** [comment]
Yeah, don't know how `undefined` would happen either ...

**Comment by alexristich** [comment]
Ah, good point - that makes way more sense. Still no idea why it gets the value of undefined, but the falsy check seems to work.

I opted to keep the existing structure where it returns early if `trackerInfo` has the value `undefined` for whatever reason.

**Comment by ghostwords** [comment]
Looks good to me. Thanks!

**Comment by ghostwords** [comment]
Oh, maybe the error happens when (1) PB is disabled or social widgets are disabled, since then the widget list doesn't get sent, and (2) PB blocks a request.
(1) In `src/webrequest`:
```javascript
  } else if (request.checkReplaceButton) {
    if (badger.isPrivacyBadgerEnabled(tabHost) && badger.isSocialWidgetReplacementEnabled()) {
      var socialWidgetBlockList = getSocialWidgetBlockList();
      sendResponse(socialWidgetBlockList);
    }
```
(2) Ibid:
```javascript
    if (requestAction == constants.BLOCK || requestAction == constants.USER_BLOCK) {
      ...
      // Notify the content script...
      var msg = {
        replaceSocialWidget: true,
        trackerDomain: requestDomain
      };
      chrome.tabs.sendMessage(tab_id, msg);
```

**Comment by ghostwords** [comment]
Social widget replacement logic is due for refactoring in #931.

**Comment by alexristich** [comment]
Ah, excellent point! Yeah, that totally makes sense. I believe I was the one to actually notice and report the duplicate button issue a little over a month ago - totally didn't connect the dots that that might have been what was causing this!

So, in fact, the original code should have been fine once the widget refactoring is in place, but I guess this new code will do even "better" ;)

**Pull request merged**
