### PR TITLE
Add Public Suffix List (PSL) updating to build process

### LINKED ISSUE #936: update public suffix list
looks like it was last updated on 1/20 and there's been many changes since then: https://github.com/publicsuffix/list/commits/master

### PR DESCRIPTION
**Pull request by ghostwords**
This fixes #936 by scripting PSL updates during `make`. If `lib/publicSuffixList.js` ends up changed, Make says that and exits without completing the build.

@cooperq review plz

### CODE REVIEW

**Comment by ghostwords** [comment]
Hmm, this will break Travis when we have an out-of-date PSL ... We probably don't want that.

**Comment by ghostwords** [comment]
https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat is working for me again but it was coming back as a blank doc earlier ... let me see if we need a check for that.

**Comment by ghostwords** [comment]
Also checking on the "uk" thing ... Looks like a bunch of two char exceptions (?) were removed, not all though:
```diff
     "tp.it": 1,
-    "tr": 2,
+    "tr.eu.org": 1,
     "tr.it": 1,
...
-    "uk": 2,
     "uk.com": 1,
+    "uk.eu.org": 1,
...
     "z.se": 1,
-    "za": 2,
+    "za.bz": 1,
     "za.com": 1,
```

**Comment by ghostwords** [comment]
Here is the most recent relevant commit for "uk" (found with `git log -G '\*\.uk\b'` in the PSL repo): https://github.com/publicsuffix/list/commit/274e07a82611bede81f8af2f475abc0bb97790fb. @cooperq does this explain it?

**Comment by cooperq** [comment]
lgtm

**Pull request merged**
