### PR TITLE
added wildcard subdomains to whitelist settings

### PR DESCRIPTION
**Pull request by SwartzCr**
fixes issue brought up in #610

### CODE REVIEW

**Comment by SwartzCr** [comment]
for @cooperq to review
to test: run pb normal, whitelist *.taobao.com, visit world.taobao.com -- nothing happens
run with this change: see that world.taobao.com, or ju.taobao.com have pb deactivated on them

**Comment by narcolepticinsomniac** [comment]
It's not all that clear from the comments above, but it seems like you're still referring to sites being whitelisted when you visit those particular sites. The problem is with whitelisting third-party content injected into other pages. I provided examples in the other thread. Basically some sites (vk.com included) pull dozens and dozens of images per page from "vk.me". Every url has its own random prefix like: http://097624.vk.me/whatever or http://850279.vk.me/whatever.
PB treats each one as a unique domain and the only option is to allow them individually which is not any kind of real option. No content is ever pulled from vk.me without a prefix so the slider to whitelist it never appears. If that was an option, I don't know whether or not it would affect all the prefixed subdomains.
First party wildcard whitetlisting is good, but there needs to be the same option for third-party content. 
Personally I don't understand why whitelisting a site as a first party doesn't encompass any content they're loading into other pages. You've already given them you're seal of approval, which is either because you trust them or because blocking them screws things up. Either way, whichever reason you have for doing so most likely applies to their third-party content as well.

**Comment by SwartzCr** [comment]
@cooperq feel free to ignore this until I get the tests to pass
@narcolepticinsomniac Sorry, there was a different issue requesting wildcard whitelisting (though I can't find it).
As far as the feature you're asking for you should be able to toggle that in the options menu, where you will see the base domain for a given third party listed. If you set it to green it will apply to all subdomains.

**Comment by narcolepticinsomniac** [comment]
I guess guess I have my answer as to whether or not whitelisting the base domain would affect those  with prefixes. It doesn't. It still treats them as unique. Damn.

**Comment by cooperq** [comment]
@SwartzCr are you still working on this?

**Comment by cooperq** [comment]
huh, the tests seem to pass on my local. re-running travis now. Looks good otherwise. Once travis passes I will merge.

**Pull request merged**
