### PR TITLE
Restyle error reporting popup

### PR DESCRIPTION
**Pull request by taravancil**
In addition to restyling the popup, this adds a feature to notify the
user whether or not their report was submitted successfully.

### CODE REVIEW

**Comment by taravancil** [comment]
Let me know what you think of the new layout. Happy to make changes!

**Comment by SwartzCr** [comment]
Looks good, two minor nit-picks and then I'm happy to merge
The success marker only gets reset when the whole window is closed, not when the overlay goes away, it'd be nice to add a $("#report_success").toggleClass("hidden"); to the overlay close

also, <span id="report_close" class="i18n_report_close"></span>, isn't a 'button' so the mouse cursor over it is the same as it would be over text, rather than a pointer, that'd be swell if that could be changed too.

Other than that, it looks great!
Once those changes are in I'm happy to merge, would you be willing to do this in Firefox as well, I can point you to where the overlay code is there if so

**Comment by taravancil** [comment]
Ok, this should address the two nit-picks!

**Comment by SwartzCr** [comment]
looks great!

**Pull request merged**
